"""wip

Revision ID: 6e66203216f4
Revises: 
Create Date: 2025-12-18 15:40:42.312337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e66203216f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('creation_ip', sa.String(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'COMPLETED', 'FAILED', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(), nullable=False),
    sa.Column('dst', sa.String(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('rename', sa.String(), nullable=True),
    sa.Column('notif_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
